server:
  port: 8088
jwt:
  secret: testingkey
  validity:
     access: 10
     refresh: 30
spring:  
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081/
          predicates:
          - Path=/clinic-service/**
          filters:
            - AuthenticationFilter
          